---
vagrant:
  vm:
    hostname: "project.local.de"
    memory: '1024'
    cpus: '1'
    provider: virtualbox

config:
  php-version: 5.4
  install-zendguardloader: true
  install-ioncubeloader: true
  install-elasticsearch: true



