---
config:
  hostname: "test.local"
  php-version: 5.6
  install-zendguardloader: true
  install-ioncubeloader: true
  install-elasticsearch: false
  use-shared-folder: true
  vm:
    provider: virtualbox
    memory: '1024'
    cpus: '1'
    #private_network_ip: 192.168.42.110
    #private_network_gateway: 192.168.42.1



