---
### This is the single-vm configuration
config:
  # hostname setting
  hostname: 'my.project'
  # project folder that is linked to docroot
  webroot: 'web'
  # php-version possible options  ['5.3'|'5.4'|'5.5'|'5.6'|'7.0']
  php-version: '5.5'
  # should zend guard loader be installed [true|false]
  install-zendguardloader: true
  # should ioncube loader be installed [true|false]
  install-ioncubeloader: true
  # should elasticsearch be installed [true|false]
  install-elasticsearch: true
  # which version of elastic should be installed [0.90 up to current, defaults to 1.4]
  # ATTENTION: If you've a tailing null you must put the version into single quotes!
  elastic-version: '1.4'
  # create symlink from shared folder for webroot [true|false]
  use-shared-folder: true
  vm:
    # vm provider ['virtualbox'|'vmware_workstation'|'vmware_fusion']
    provider: 'virtualbox'
    # memory assigned to vm
    memory: '1024'
    # cpus assigned to vm
    cpus: '1'
    # customize network ip default is 192.168.42.100 for virtualbox and 192.168.33.100 for vmware
    private_network_ip: 192.168.42.110

### And this one is for multiple VMs
config:
  # VM provider ['virtualbox'|'vmware_workstation'|'vmware_fusion']
  provider: virtualbox
  # The hostname of you VM
  hostname: test-vm.dev
  # Nodes to manage
  nodes:
    # This is the name of the node
    db:
      # Specifies the Puppet script for this node. If it's not given the name of the node will be used.
      # Predefined scripts: apache, mysql, elastic
      manifest: mysql
      # VM configuration
      vm:
        # memory assigned to vm in MiB
        memory: 1024
        # Number of CPUs assigned to VM
        cpus: 2
        # Customize network ip default is 192.168.42.100 for VirtualBox and 192.168.33.100 for VMware
        private_network_ip: 192.168.42.92
    http:
      manifest: apache
      # project folder that is linked to docroot
      webroot: web
      # PHP version possible options ['5.3'|'5.4'|'5.5'|'5.6'|'7.0']
      php-version: '7.0'
      # Port for the web server
      vhost-port: 80
      # Should ZendGuardLoader (ZGL) be installed [true|false]
      install-zendguardloader: true
      # Should IonCube loader be installed [true|false]
      install-ioncubeloader: false
      # create symlink from shared folder for webroot [true|false]
      use-shared-folder: true
      vm:
        memory: 512
        cpus: 1
        private_network_ip: 192.168.42.91
    elastic:
      manifest: elastic
      # which version of elastic should be installed [0.90 up to current, defaults to 1.4]
      # ATTENTION: If you've a tailing null you must put the version into single quotes!
      elastic-version: '1.7'
      vm:
        memory: 1024
        cpus: 1
        private_network_ip: 192.168.42.93
    proxy:
      # Mark this VM as the default one
      primary: true
      # Define your proxies here
      # Each proxy nust contain a location (which is the "path" part of the URL) and a link to a node.
      # If the target service is accessable on another port than 80 you can specify it with the "port" key.
      proxies:
        - { location: /, node: http }
        - { location: /es, node: elastic, port: 9200 }
      vm:
        memory: 256
        cpus: 1
        private_network_ip: 192.168.42.90
